#!/bin/bash
#
# Install Moodle 3.10.1 and client requested plugins on Ubuntu 18.04.
# This script must be run as root (ex.: sudo sh [script_name])
# Style Guide: https://google.github.io/styleguide/shellguide.html

# Parameters: all manadatory and must be prefix with "--" on command line.
declare -A parameters=( \
  [data_disk_size]= \
  [data_disk_mount_point_path]= \
  [db_server_admin_password]= \
  [db_server_admin_username]= \
  [db_server_fqdn]= \
  [db_server_matomo_db_name]= \
  [db_server_matomo_password]= \
  [db_server_matomo_username]= \
  [db_server_name]= \
  [max_execution_time]= \
  [smtp_server_fqdn]= \
  [smtp_server_private_ip]= \
  [web_server_fqdn]= \
)

# Constants

# Functions
source ./utils.sh

function utils::mysql_create_client_options_file() {
  local username="$1"
  local password="$2"
  local host="$3"
  local port="$4"
  local database="$5"
  local file_path="$6"

  utils::echo_action "Creating mysql config file: ${file_path}..."
  if [[ -f "${file_path}" ]]; then
    utils::echo_error "The file ${file_path} already exists. Aborting."
    exit 1
  fi

  touch "${file_path}"
  chmod 600 "${file_path}"
  cat <<EOF > "${file_path}"
[client]
host="${host}"
port="${port}"
user="${username}@${host%%.*}"
password="${password}"
database="${database}"
EOF

}

function utils::mysql_create_database_if_not_exists() {
  local admin_username="$1"
  local admin_password="$2"
  local host="$3"
  local port="$4"
  local database="$5"

  readonly local CLIENT_OPTIONS_FILE_PATH=="/tmp/my.cnf"

  utils::mysql_create_client_options_file \
    "${admin_username}" \
    "${admin_password}" \
    "${host}" \
    "${port}" \
    "mysql" \
    "${CLIENT_OPTIONS_FILE_PATH}"

  utils::echo_action "Creating new MySQL database if not existing: ${database}..."
  mysql --defaults-extra-file="${CLIENT_OPTIONS_FILE_PATH}" --execute "WARNINGS; CREATE DATABASE IF NOT EXISTS ${database};"

  utils::echo_action "Deleting temporary mysql config file: ${mysql_connection_file_path}..."
  rm "${CLIENT_OPTIONS_FILE_PATH}"
}

function utils::mysql_create_user_if_not_exists() {
  local admin_username="$1"
  local admin_password="$2"
  local host="$3"
  local port="$4"
  local user_username="$5"
  local user_password="$6"

  readonly local CLIENT_OPTIONS_FILE_PATH="/tmp/my.cnf"

  utils::mysql_create_client_options_file \
    "${admin_username}" \
    "${admin_password}" \
    "${host}" \
    "${port}" \
    "mysql" \
    "${CLIENT_OPTIONS_FILE_PATH}"

  utils::echo_action "Creating MySQL database user if not exising: ${user_username}..."
  mysql --defaults-extra-file=${CLIENT_OPTIONS_FILE_PATH} \
    --execute "WARNINGS; CREATE USER IF NOT EXISTS ${user_username} IDENTIFIED BY '${user_password}';"

  utils::echo_action "Deleting temporary mysql config file: ${mysql_connection_file_path}..."
  rm "${CLIENT_OPTIONS_FILE_PATH}"
}

function utils::mysql_grant_all_privileges() {
  local admin_username="$1"
  local admin_password="$2"
  local host="$3"
  local port="$4"
  local database="$5"
  local user_username="$6"

  readonly local CLIENT_OPTIONS_FILE_PATH=="/tmp/my.cnf"

  utils::mysql_create_client_options_file \
    "${admin_username}" \
    "${admin_password}" \
    "${host}" \
    "${port}" \
    "mysql" \
    "${CLIENT_OPTIONS_FILE_PATH}"

  utils::echo_action "Granting all privileges on all ${database} database objects to user '${user_username}'..."
  mysql --defaults-extra-file="${CLIENT_OPTIONS_FILE_PATH}" \
    --execute "WARNINGS; GRANT ALL PRIVILEGES ON ${database}.* TO ${user_username}; FLUSH PRIVILEGES;"

  utils::echo_action "Deleting mysql config file: ${file_path}..."
  rm "${CLIENT_OPTIONS_FILE_PATH}"
}

function main() {

  readonly local APACHE2_CONF_ENABLED_SECURITY_FILE_PATH="/etc/apache2/conf-enabled/security.conf"
  readonly local APACHE2_DEFAULT_DOCUMENT_ROOT_DIR_PATH="/var/www/html"
  readonly local APACHE2_DEFAULT_SITE_CONFIG_FILE_NAME="000-default.conf"
  readonly local APACHE2_MATOMO_SITE_CONFIG_FILE_NAME="matomo.conf"
  readonly local APACHE2_PHP_INI_FILE_PATH="/etc/php/7.2/apache2/php.ini"
  readonly local APACHE2_SITES_AVAILABLE_PATH="/etc/apache2/sites-available"
  readonly local APACHE2_SITES_ENABLED_PATH="/etc/apache2/sites-enabled"
  readonly local APACHE2_USER="www-data"

  local matomo_document_root_dir_path
  local working_dir

  utils::set_exit_trap
  utils::echo_title "Start of $0"

  #############################################################################

  utils::echo_title "Parse Input Parameters"
  utils::parse_parameters "$@"

  #############################################################################

  utils::echo_title "Set Global Variables"
  utils::echo_action "Setting matomo_document_root_dir_path..."
  matomo_document_root_dir_path="${parameters[data_disk_mount_point_path]}/matomo"
  utils::echo_action "Setting working_dir..."
  working_dir=$(pwd)
  utils::echo_info "Done."

  #############################################################################

  utils::echo_title "Mount Data Disk"
  utils::mount_data_disk_by_size \
    "${parameters[data_disk_size]}" \
    "${parameters[data_disk_mount_point_path]}"

  #############################################################################

  utils::echo_title "Download and Extract Matomo Files"
  # Ref.: https://builds.matomo.org/
  if [[ -d "${matomo_document_root_dir_path}" ]]; then
    utils::echo_info "Skipped: Matomo already installed."
  else
    utils::echo_action "Downloading Matomo 3.11 tar file..."
    wget https://builds.matomo.org/matomo-3.11.0.tar.gz
    utils::echo_info "Done."

    utils::echo_action "Extracting Matomo tar file..."
    tar zxf matomo-3.11.0.tar.gz -C "${parameters[data_disk_mount_point_path]}"
    utils::echo_info "Done."
  fi

  #############################################################################

  utils::echo_title "Install tools"
  utils::echo_action "Installing mysql-client..."
  apt-get install --yes --quiet \
    mysql-client-5.7
  utils::echo_info "Done."

  #############################################################################

  utils::echo_title "Install Matomo Dependencies"

  utils::echo_action "Installing apache2 packages..."
  apt install --yes --quiet \
    apache2 \
    libapache2-mod-php
  utils::echo_info "Done."

  utils::echo_action "Installing php packages..."
  apt install --yes --quiet \
    php-cli \
    php-gd \
    php-json \
    php-mbstring \
    php-mysql \
    php-xml

  utils::echo_action "Installing libmaxminddb packages..."
  # ref.: https://fr.matomo.org/faq/how-to/faq_164/
  # Ref.: https://github.com/maxmind/libmaxminddb/blob/master/README.md#on-ubuntu-via-ppa
  add-apt-repository --yes ppa:maxmind/ppa
  apt update
  apt install --yes --quiet \
    libmaxminddb0 \
    libmaxminddb-dev \
    mmdb-bin

  utils::echo_info "Done."

  #############################################################################

  utils::echo_title "Map SMTP Server Private IP"
  utils::add_hosts_file_entry \
    "${parameters[smtp_server_private_ip]}" \
    "${parameters[smtp_server_fqdn]}" \
    "Redirect SMTP Server FQDN to Private IP Address."

  #############################################################################

  utils::echo_title "Update Apache2's PHP Configuration"

  # Ref. https://matomo.org/docs/setup-auto-archiving/#important-tips-for-medium-to-high-traffic-websites
  # Values required to run report on 12 months of data.
  utils::update_php_config_file \
    "memory_limit" \
    "2048M" \
    "${APACHE2_PHP_INI_FILE_PATH}"
  utils::update_php_config_file \
    "max_execution_time" \
    "${parameters[max_execution_time]}" \
    "${APACHE2_PHP_INI_FILE_PATH}"

  #############################################################################

  utils::echo_title "Set Up Apache2"

  utils::echo_action "Creating Matomo site configuration file using Apache2 Default site configuration file as template..."
  # Use the Default site config file as a template.
  cp "${APACHE2_SITES_AVAILABLE_PATH}/${APACHE2_DEFAULT_SITE_CONFIG_FILE_NAME}" "${APACHE2_SITES_AVAILABLE_PATH}/${APACHE2_MATOMO_SITE_CONFIG_FILE_NAME}"

  # Updating matomo site config DocumentRoot.
  utils::update_apache2_config_file \
    "DocumentRoot" \
    "${matomo_document_root_dir_path}" \
    "${APACHE2_SITES_AVAILABLE_PATH}/${APACHE2_MATOMO_SITE_CONFIG_FILE_NAME}"

  utils::echo_action "Enabling Matomo Site..."
  if [[ -L "${APACHE2_SITES_ENABLED_PATH}/${APACHE2_MATOMO_SITE_CONFIG_FILE_NAME}" ]]; then
    utils::echo_info "Skipped: Matomo site already enabled."
  else
    ln -s "${APACHE2_SITES_AVAILABLE_PATH}/${APACHE2_MATOMO_SITE_CONFIG_FILE_NAME}" "${APACHE2_SITES_ENABLED_PATH}/${APACHE2_MATOMO_SITE_CONFIG_FILE_NAME}"
    utils::echo_info "Done."
  fi

  ### Experiment
  a2ensite "${APACHE2_MATOMO_SITE_CONFIG_FILE_NAME%%.conf}"

  utils::echo_action "Disabling default site..."
  if [[ -L "${APACHE2_SITES_ENABLED_PATH}/${APACHE2_DEFAULT_SITE_CONFIG_FILE_NAME}" ]]; then
    rm "${APACHE2_SITES_ENABLED_PATH}/${APACHE2_DEFAULT_SITE_CONFIG_FILE_NAME}"
    utils::echo_info "Done."
  else
    utils::echo_info "Skipped: Default site already disabled."
  fi

  ### Experiment
  a2dissite "${APACHE2_DEFAULT_SITE_CONFIG_FILE_NAME%%.conf}"

  utils::echo_action "Hardening web werver..."
  utils::harden_apache2 "${APACHE2_CONF_ENABLED_SECURITY_FILE_PATH}"

  utils::echo_action 'Setting file permissions...'
  chown -R "${APACHE2_USER}:root" "${matomo_document_root_dir_path}"
  chmod -R 775 "${matomo_document_root_dir_path}"
  utils::echo_info "Done."

  utils::echo_action "Restarting Apache2..."
  service apache2 restart
  utils::echo_info "Done."

  #############################################################################

  utils::echo_title "Setup MySQL Database"

  utils::mysql_create_user_if_not_exists \
    "${parameters[db_server_admin_username]}" \
    "${parameters[db_server_admin_password]}" \
    "${parameters[db_server_fqdn]}" \
    "3306" \
    "${parameters[db_server_matomo_username]}" \
    "${parameters[db_server_matomo_password]}"

  utils::mysql_grant_all_privileges \
    "${parameters[db_server_admin_username]}" \
    "${parameters[db_server_admin_password]}" \
    "${parameters[db_server_fqdn]}" \
    "3306" \
    "${parameters[db_server_matomo_db_name]}" \
    "${parameters[db_server_matomo_username]}"

  #############################################################################

  utils::echo_title "Matomo Post Installation Process"

  matomo_archive_crontab_entry_path="/etc/cron.d/matomo-archive"
  matomo_archive_log_path="/var/log/matomo-archive.log"

  utils::echo_action "Setting up Matomo Archive Crontab..."
  # Ref.: See section "Launching multiple archivers at once" in
  #       https://matomo.org/docs/setup-auto-archiving/#linux-unix-how-to-set-up-a-crontab-to-automatically-archive-the-reports
  if [[ -f ${matomo_archive_crontab_entry_path} ]]; then
      utils::echo_info "Skipped: Matomo Archive Crontab already exist."
  else
      for archiver_id in {1..2}
      do
          touch ${matomo_archive_log_path}.${archiver_id}
          chown ${APACHE2_USER} ${matomo_archive_log_path}.${archiver_id}
          echo "${archiver_id} * * * * ${APACHE2_USER} /usr/bin/php ${matomo_document_root_dir_path}/console core:archive --url=https://${parameters[web_server_fqdn]} > ${matomo_archive_log_path}.${archiver_id} 2>&1" >> ${matomo_archive_crontab_entry_path}
      done
      utils::echo_info "Done."
  fi

  #############################################################################

  utils::echo_title "End of $0"
  utils::unset_exit_trap
}

main "$@"
