#!/bin/bash
#
# Install or Update Matomo on Ubuntu 20.04.
# This script must be run as root (ex.: sudo sh [script_name])
# Style Guide: https://google.github.io/styleguide/shellguide.html

# Functions
source ./apache2.sh
source ./logger.sh
source ./mysql.sh
source ./os.sh
source ./php.sh
source ./utils.sh

# Constant
PHP_VERSION="8.3"

######################################
# Install packages required to complete matomo installation.
# Arguments: None
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function install_utilities() {
  logger::action "Installing packages..."
  apt-get install --yes --quiet \
    gpg \
    mysql-client \
    software-properties-common \
    vim
}

######################################
# Install packages required to run matomo.
# Arguments: None
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function install_matomo_dependencies() {
  # Ref.: https://matomo.org/docs/requirements/
  #       https://fr.matomo.org/faq/how-to/faq_164/
  #       https://github.com/maxmind/libmaxminddb/blob/master/README.md#on-ubuntu-via-ppa

  logger::action "Adding package repositories..."
  add-apt-repository --yes ppa:maxmind/ppa

  logger::action "Update package repository definition..."
  apt update

  logger::action "Installing packages..."
  apt install --yes --quiet \
    cron \
    libmaxminddb-dev \
    libmaxminddb0 \
    mmdb-bin \
    nginx \
    php${PHP_VERSION}-cli \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-fpm \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-mysql \
    php${PHP_VERSION}-xml
}

######################################
# Assess whether an update is required based on a current and a desired version.
# Both version values must respect the Sementic Versioning. Ref.: https://semver.org
# Arguments:
# - The current version, a string.
# - The desired version, a string.
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
#   Returns 0 if an update is required and 1 otherwise.
######################################
function is_update_required() {
  # Parameters
  local current_version="${1}"
  local desired_version="${2}"

  function validate_version() {
    # Parameters
    local name="${1}"
    local value="${2}"

    if ! grep -q -E '^[0-9]+\.[0-9]+\.[0-9]+$' <<< "${value}"; then
      logger::error "The ${name} (${value}) does not respect Semetic Versioning. Aborting."
      exit 1
    fi
  }

  # Echo input parameters.
  logger::debug "Current version: ${current_version}"
  logger::debug "Desired version: ${desired_version}"

  # Validate input paramters
  validate_version "current_version" "${current_version}"
  validate_version "desired_version" "${desired_version}"

  # Check if versions are equal first.
  if [[ "${current_version}" == "${desired_version}" ]]; then
    logger::info "Current version ($1) is matching the desired version ($2)."
    return 1
  fi

  # Add a final dot to version values (a stop condition for the loop below).
  current_version="${current_version}."
  desired_version="${desired_version}."

  # Loop through sementic version tokens.
  while [[ -n "${current_version}" ]]; do

    current_version_token="${current_version%%.*}"
    desired_version_token="${desired_version%%.*}"

    logger::debug "Current version token: ${current_version_token}"
    logger::debug "Desired version token: ${desired_version_token}"

    if [[ "${current_version_token}" -lt "${desired_version_token}" ]]; then
      logger::info "Current version ($1) is older than desired version ($2)."
      return 0
    elif [[ "${current_version_token}" -gt "${desired_version_token}" ]]; then
      logger::info "Current version ($1) is not older than desired version ($2)."
      return 1
    else
      # Tokens are equal. Move to next sementic version token.
      current_version="${current_version#*.}"
      desired_version="${desired_version#*.}"
    fi
  done

  # Should never reach this point.
  exit 1
}

######################################
# Download, extract and set permission on matomo files.
# Arguments:
# - The Matomo home directory path, a string.
# - The Matomo version to download, a string.
# - The owner for the matomo files, a string.
# - The group for the matomo files, a string.
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function deploy_matomo_files() {
  # Parameters
  local matomo_home_path="${1}"
  local matomo_version="${2}"
  local matomo_file_owner="${3}"
  local matomo_file_group="${4}"

  # Constants
  local -r MATOMO_PACKAGE_FILE_URL="https://builds.matomo.org/matomo-${matomo_version}.tar.gz"

  # Variables
  local matomo_package_file_name
  local extraction_path

  logger::action "Downloading Matomo package and signature files..."
  # Ref.: https://matomo.org/blog/2014/11/verify-signatures-piwik-packages/
  wget "${MATOMO_PACKAGE_FILE_URL}"
  wget "${MATOMO_PACKAGE_FILE_URL}.asc"

  logger::action "Downloading and installing Matomo packages' signing certificate..."
  gpg --keyserver keyserver.ubuntu.com --recv-keys F529A27008477483777FC23D63BB30D0E5D2C749

  logger::action "Checking Matomo package file integrity and origin..."
  matomo_package_file_name=$(basename "${MATOMO_PACKAGE_FILE_URL}")
  if ! gpg --verify "${matomo_package_file_name}"{.asc*,};  then
    logger::error "Downloaded Matomo package file fails signature check. Aborting."
    exit 1
  fi

  logger::action "Extracting Matomo package files..."
  extraction_path="$(dirname "${matomo_home_path}")"
  tar zxf "${matomo_package_file_name}" -C "${extraction_path}"

  logger::action "Setting file ownership and permissions on ${matomo_home_path}..."
  chown -R "${matomo_file_owner}:${matomo_file_group}" "${matomo_home_path}"
  chmod -R 775 "${matomo_home_path}"
}

######################################
# Perform a fresh install or update the current version of Matomo.
# Arguments:
# - The Matomo home directory path, a string
# - The Matomo desired version, a string.
# - The owner for the matomo files, a string.
# - The group for the matomo files, a string.
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
install_or_update_matomo() {
  # Parameters
  local matomo_home_path="${1}"
  local matomo_desired_version="${2}"
  local matomo_file_owner="${3}"
  local matomo_file_group="${4}"

  # Variables
  local matomo_current_version

  logger::action "Looking for an existing Matomo configuration file..."
  if [[ -f "${matomo_home_path}/config/config.ini.php" ]]; then
    logger::info "A Matomo configuration file found."

    logger::action "Getting Matomo's current version..."
    matomo_current_version="$(runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" core:version | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$')"
    logger::info "Matomo's current version is ${matomo_current_version}."

    logger::action "Assessing whether an update is required..."
    if is_update_required "${matomo_current_version}" "${matomo_desired_version}"; then
      logger::info "An update is required."

      logger::action "Turning Matomo maintenance mode on and stoping web site tracking..."
      runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" config:set General.maintenance_mode=1 --ignore-warn
      runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" config:set Tracker.record_statistics=0 --ignore-warn

      logger::action "Updating Matomo file system..."
      deploy_matomo_files "${matomo_home_path}" "${matomo_desired_version}" "${matomo_file_owner}" "${matomo_file_group}"

      logger::action "Updating Matomo core..."
      runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" core:update --yes --verbose --no-interaction --ignore-warn

      logger::action "Removing unexpected files, if any..."
      runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" diagnostics:unexpected-files --delete --no-interaction

      logger::action "Turning maintenance mode off and resuming web site tracking..."
      runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" config:set General.maintenance_mode=0
      runuser -u "${matomo_file_owner}" -- "${matomo_home_path}/console" config:set Tracker.record_statistics=1
    else
      logger::info "No update required. Skipping the update process."
    fi
  else
    logger::info "No Matomo configuration file not found. Moving on with a clean install."

    logger::action "Removing all traces of previous partial installation process."
    rm -rf "${matomo_home_path}"

    logger::action "Installing Matomo file system..."
    deploy_matomo_files "${matomo_home_path}" "${matomo_desired_version}" "${matomo_file_owner}" "${matomo_file_group}"
  fi
}


######################################
# Set up php client.
# These parameters are used when Matomo's console core:archive jobs are started by crontab.
# Arguments:
# - The PHP max execution time value, an integer.
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function set_up_php_client() {

  # Parameters
  local php_max_execution_time="${1}"

  # Constant
  local -r PHP_INI_FILE_PATH="/etc/php/${PHP_VERSION}/cli/php.ini"

  logger::action "Updating PHP Client configuration..."
  # Ref. https://matomo.org/docs/setup-auto-archiving/#important-tips-for-medium-to-high-traffic-websites
  # Values required to run report on 12 months of data.
  php::update_config_file "memory_limit" "4096M" "${PHP_INI_FILE_PATH}"
  php::update_config_file "max_execution_time" "${php_max_execution_time}" "${PHP_INI_FILE_PATH}"
  php::update_config_file "max_input_vars" "2000" "${PHP_INI_FILE_PATH}"
}

######################################
# Set up php fpm.
# These parameters are used when nginx is serving php pages.
# Arguments: none
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function set_up_php_fpm() {

  # Constant
  local -r PHP_FPM_POOL_CONF="/etc/php/${PHP_VERSION}/fpm/pool.d/www.conf"

  # Variables
  local max_children
  local max_requests
  local max_spare_servers
  local memory_total
  local min_spare_servers
  local process_manager
  local processor_count
  local start_servers

  # Update PHP FPM pool settings.
  # Ref. : https://tideways.com/profiler/blog/an-introduction-to-php-fpm-tuning

  logger::action "Getting the server processor count..."
  processor_count="$(grep -c "processor" /proc/cpuinfo)"
  logger::info "${processor_count} processor(s) detected."

  logger::action "Getting the server memory size..."
  memory_total="$(awk '/MemTotal/ {print $2}' /proc/meminfo)"
  logger::info "${memory_total} MB detected."

  # Use dynamic process manager.
  process_manager="dynamic"
  logger::action "Setting process manager to ${process_manager}..."
  php::update_config_file "pm" "${process_manager}" "${PHP_FPM_POOL_CONF}"

  # Set max_children = (Total RAM – Memory used for Linux, DB, etc.) / process size
  max_children=$(( ((memory_total / 1024) - 2048) / 128 ))
  logger::action "Setting process manager max_children to ${max_children}..."
  php::update_config_file "pm.max_children" "${max_children}" "${PHP_FPM_POOL_CONF}"

  # Set start_servers = Number of CPU cores x 4
  start_servers=$(( processor_count * 4 ))
  logger::action "Setting process manager start_servers	to ${start_servers}..."
  php::update_config_file "pm.start_servers" "${start_servers}" "${PHP_FPM_POOL_CONF}"

  # Set min_spare_servers = Number of CPU cores x 2
  min_spare_servers=$(( processor_count * 2 ))
  logger::action "Setting process manager min_spare_servers to ${min_spare_servers}..."
  php::update_config_file "pm.min_spare_servers" "${min_spare_servers}" "${PHP_FPM_POOL_CONF}"

  # Set max_spare_servers = Same as start_servers
  max_spare_servers=${start_servers}
  logger::action "Setting process manager max_spare_servers to ${max_spare_servers}..."
  php::update_config_file "pm.max_spare_servers" "${max_spare_servers}" "${PHP_FPM_POOL_CONF}"

  # Set max_requests = Explicitly use default value (500)
  max_requests=500
  logger::action "Setting process manager max_requests to ${max_requests}..."
  php::update_config_file "pm.max_requests" ${max_requests} "${PHP_FPM_POOL_CONF}"
}

######################################
# Set up nginx for matomo.
# Arguments: None
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function set_up_nginx() {

  logger::action "Copying Matomo Web site configuration file..."
  cp "./matomo.conf" "/etc/nginx/sites-available/matomo.conf"
  chmod 644 "/etc/nginx/sites-available/matomo.conf"

  logger::action "Enabling Matomo site..."
  if  [[ -L "/etc/nginx/sites-enabled/matomo.conf" ]]; then
    logger::info "Matomo site already enabled. Skipping."
  else
    ln -s "/etc/nginx/sites-available/matomo.conf" "/etc/nginx/sites-enabled/matomo.conf"
  fi

  logger::action "Disabling Default site..."
  if [[ ! -e "/etc/nginx/sites-enabled/default" ]]; then
    logger::info "Default site already disabled. Skipping."
  else
    rm "/etc/nginx/sites-enabled/default"
  fi

  logger::action "Restarting Nginx..."
  service nginx restart
}

######################################
# Set up Matomo specific crontabs.
# Arguments:
# - The matomo home path, a string.
# - The Matomo file owner, a string.
# - The web server FQDN, a string
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function set_up_crontab() {
  # Parameters
  local matomo_home_path="${1}"
  local matomo_file_owner="${2}"
  local web_server_fqdn="${3}"

  # Constants
  local -r MATOMO_ARCHIVE_CRONTAB_ENTRY_PATH="/etc/cron.d/matomo-archive"
  local -r MATOMO_ARCHIVE_LOG_FILE_PATH="/var/log"
  local -r MATOMO_ARCHIVE_LOG_FILE_PREFIX="matomo-archive"
  local -r MATOMO_ARCHIVE_LOG_FILE_EXTENSION="log"

  # Variables
  local dailyLogFilePath;

  if [[ -f "${MATOMO_ARCHIVE_CRONTAB_ENTRY_PATH}" ]]; then
      logger::warn "Skipped: Matomo Archive Crontab already exist."
  else
      # Set only one archiver job as multiple concurent archivers tend to overload database server resources.
      # Store job's log in distinct log file for every day of the week. (Effectively keeping 7 days worth of logs.)

      # Create empty log files for every day of the week with proper file ownership.
      for day in {Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday}; do
        dailyLogFilePath="${MATOMO_ARCHIVE_LOG_FILE_PATH}/${MATOMO_ARCHIVE_LOG_FILE_PREFIX}.${day}.${MATOMO_ARCHIVE_LOG_FILE_EXTENSION}"
        touch "${dailyLogFilePath}"
        chown "${matomo_file_owner}" "${dailyLogFilePath}"
      done

      # Create cron tab entries with a dynamically created daily log file path.
      dailyLogFilePath="${MATOMO_ARCHIVE_LOG_FILE_PATH}/${MATOMO_ARCHIVE_LOG_FILE_PREFIX}.\$(date +\\%A).${MATOMO_ARCHIVE_LOG_FILE_EXTENSION}"
      # Purge archiver daily log file at midnight every day.
      echo "0 0 * * * ${matomo_file_owner} printf '' > ${dailyLogFilePath}" >> "${MATOMO_ARCHIVE_CRONTAB_ENTRY_PATH}"
      # Run archiver job on the 1st minute of every hour and append log in the daily log file.
      echo "1 * * * * ${matomo_file_owner} /usr/bin/php ${matomo_home_path}/console core:archive --url=https://${web_server_fqdn} --concurrent-requests-per-website=1 >> ${dailyLogFilePath} 2>&1" >> "${MATOMO_ARCHIVE_CRONTAB_ENTRY_PATH}"

      logger::info "Done."
  fi
}

######################################
# The main installation script.
# Arguments:
# - The data disk size, an integer.
# - The database server administrator password, a string.
# - The database server administrator username, a string.
# - The database server fully qualified domain name, a string.
# - The matomo database name, a string.
# - The matomo database password, a string.
# - The matomo database username, a string.
# - The matomo version to install, a string. The value must respect the Sementic Versioning. Ref.: https://semver.org
# - The PHP max execution time value, an integer.
# - The SMTP service fully qualified domain name, a string.
# - The Web server fully qualified domain name, a string.
# Outputs:
#   Writes message to STDOUT or STDERR based on message level.
######################################
function main() {
  # Parameters: all mandatory and must be prefixed with "--" on command line.
  declare -A parameters=( \
    [data_disk_size]="" \
    [db_server_admin_password]="" \
    [db_server_admin_username]="" \
    [db_server_fqdn]="" \
    [matomo_database_name]="" \
    [matomo_database_password]="" \
    [matomo_database_username]="" \
    [matomo_version]="" \
    [php_max_execution_time]="" \
    [smtp_server_fqdn]="" \
    [web_server_fqdn]="" \
  )

  # Constants
  DATA_DISK_MOUNT_POINT_PATH="/var/www/html"
  MATOMO_FILE_GROUP="www-data"
  MATOMO_FILE_OWNER="www-data"
  MATOMO_HOME_PATH="${DATA_DISK_MOUNT_POINT_PATH}/matomo"

  utils::set_exit_trap
  logger::title "Start of $0"

  #############################################################################

  logger::title "Parse Input Parameters"
  utils::parse_parameters "$@"

  logger::title "Install Utilities"
  install_utilities

  logger::title "Install Matomo Dependencies"
  install_matomo_dependencies

  logger::title "Mount Data Disk"
  os::mount_data_disk_by_size \
    "${parameters[data_disk_size]}" \
    "${DATA_DISK_MOUNT_POINT_PATH}"

  logger::title "Setup Matomo Database and Credentials"
  mysql::create_database_and_credentials \
    "${parameters[db_server_fqdn]}" \
    "${parameters[db_server_admin_username]}" \
    "${parameters[db_server_admin_password]}" \
    "${parameters[matomo_database_username]}" \
    "${parameters[matomo_database_password]}" \
    "${parameters[matomo_database_name]}"

  logger::title "Install or Update Matomo"
  install_or_update_matomo \
    "${MATOMO_HOME_PATH}" \
    "${parameters[matomo_version]}" \
    "${MATOMO_FILE_OWNER}" \
    "${MATOMO_FILE_GROUP}"

  logger::title "Set Up PHP Client"
  set_up_php_client \
    "${parameters[php_max_execution_time]}"

  logger::title "Set Up PHP FPM"
  set_up_php_fpm

  logger::title "Set Up Nginx"
  set_up_nginx

  logger::title "Set up Matomo Archive Crontab..."
  set_up_crontab \
    "${MATOMO_HOME_PATH}" \
    "${MATOMO_FILE_OWNER}" \
    "${parameters['web_server_fqdn']}"

  #############################################################################

  logger::title "End of $0"
  utils::unset_exit_trap
}

main "$@"
