#!/bin/bash
#
# Setup Matomo Single Node Web Server.
# This script must be run as root (ex.: sudo sh ./[script_name])
# Style Guide: https://google.github.io/styleguide/shellguide.html

# The function libraries and the upgrade_server script are injected on the
# server at deployment time by the Azure Resource Manager (ARM).
# See the ARM template deployment parameters for the exact version used.

# Functions

# All libraries not available at build time.
# shellcheck source=/dev/null
source ./logger.sh
# shellcheck source=/dev/null
source ./utils.sh

function main() {
  # Parameters: all manadatory and must be prefixed with "--" on command line.
  declare -A parameters=(\
    [data_disk_size]="" \
    [db_server_admin_password]="" \
    [db_server_admin_username]="" \
    [db_server_fqdn]="" \
    [matomo_database_name]="" \
    [matomo_database_password]="" \
    [matomo_database_username]="" \
    [matomo_version]="" \
    [php_max_execution_time]="" \
    [smtp_server_fqdn]="" \
    [smtp_server_from_address]="" \
    [smtp_server_password]="" \
    [smtp_server_port]="" \
    [smtp_server_username]="" \
    [web_server_admin_email]="" \
    [web_server_fqdn]="" \
    [web_server_reboot_utc_time]="" \
    [web_server_resource_name]="" \
  )

  utils::set_exit_trap
  logger::title "Start of $0"

  #############################################################################

  logger::title "Parse Input Parameters"
  utils::parse_parameters "$@"

  logger::title "Upgrade Server and Remove Unused Packages"
  ./upgrade_server

  logger::title "Install Unattended Upgrade Tools"
  ./install_unattended_upgrade_tools \
    --server_admin_email "${parameters[web_server_admin_email]}" \
    --server_fqdn "${parameters[web_server_fqdn]}" \
    --server_reboot_utc_time "${parameters[web_server_reboot_utc_time]}" \
    --server_resource_name "${parameters[web_server_resource_name]}" \
    --smtp_server_fqdn "${parameters[smtp_server_fqdn]}" \
    --smtp_server_from_address "${parameters[smtp_server_from_address]}" \
    --smtp_server_password "${parameters[smtp_server_password]}" \
    --smtp_server_port "${parameters[smtp_server_port]}" \
    --smtp_server_username "${parameters[smtp_server_username]}"

  logger::title "Install Matomo"
  ./install_matomo \
    --data_disk_size "${parameters[data_disk_size]}" \
    --db_server_admin_password "${parameters[db_server_admin_password]}" \
    --db_server_admin_username "${parameters[db_server_admin_username]}" \
    --db_server_fqdn "${parameters[db_server_fqdn]}" \
    --matomo_database_name "${parameters[matomo_database_name]}" \
    --matomo_database_password "${parameters[matomo_database_password]}" \
    --matomo_database_username "${parameters[matomo_database_username]}" \
    --matomo_version "${parameters[matomo_version]}" \
    --php_max_execution_time "${parameters[php_max_execution_time]}" \
    --smtp_server_fqdn "${parameters[smtp_server_fqdn]}" \
    --web_server_fqdn "${parameters[web_server_fqdn]}"

  #############################################################################

  logger::title "End of $0"
  utils::unset_exit_trap
}

main "$@"
