#!/bin/bash
#
# Upgrade server and remove unused packages from Ubuntu server.
# Usage
#   This script must be run as root (ex.: sudo sh ./[script_name]) and prior to
#   any server customization.
# Style Guide
#   https://google.github.io/styleguide/shellguide.html

# Functions
source ./logger.sh
source ./utils.sh

function main() {
  utils::set_exit_trap

  local waiting_time
  local -r MAX_WAIT_TIME=60

  logger::title "Start of $0"

  logger::action "Updating server package index files..."
  # Fix for issue-881.
  waiting_time=0
  while [[ $(pgrep apt) && ${waiting_time} -lt ${MAX_WAIT_TIME} ]]; do
    ((waiting_time++))
    logger::info "Waiting for other apt commands to finish: ${waiting_time} sec / ${MAX_WAIT_TIME} sec...";
    sleep 1;
  done;
  if [[ $(pgrep apt) ]]; then
    logger::error "Max waiting time reached. Aborting.";
    exit 1
  else
    apt update
  fi

  logger::action "Upgrading all installed server packages to their latest version and apply available security patches..."
  apt upgrade -y

  logger::action "Removing server packages that are no longer needed..."
  apt autoremove -y

  logger::title "End of $0"

  utils::unset_exit_trap
}

main "$@"
